### ISSUE TITLE
Using with spf13-vim name collision

### ISSUE THREAD

**Issue by seyDoggy** [kristijanhusak/vim-multiple-cursors#9]
I'm using spf13-vim distribution and I'm trying to use your fork over @terryma's but when I UnBundle terryma's and bundle yours I get a persistent Vundle error. Not your issue I know, but wondered if you had any thoughts on how to work around this.

``` sh
Error detected while processing function vundle#config#bundle..<SNR>8_check_bundle_name:
line    2:
Vundle error: Name collision for Plugin kristijanhusak/vim-multiple-cursors. Plugin terryma/vim-multiple-cursors previously used the name "vim-multiple-cursors". Skipping Plugin kristijanhusak/vim-multiple-cursors.
```

**Comment by seyDoggy** [comment]
Nevermind, I wasn't aware that Vundle had a way around this, just rename the bundle:

``` sh
Plugin 'kristijanhusak/vim-multiple-cursors', {'name': 'multiple-cursors'}
```

**Comment by kristijanhusak** [comment]
You can also go to `~/.vim/bundle` and remove multiple cursors folder and do Vundle installation again.
